version: '3.8'
services:
  database:
    image: mysql:8
    container_name: mysql_orm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myorm
      MYSQL_DATABASE: nestdb
    ports:
      - 33061:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
