version: '3.8'
services:
  database:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: postgres_container
      MYSQL_DATABASE: mypwd
    ports:
      - 5432:5432
    volumes:
      - ./data/mysql:/var/lib/mysql
